import type { PromptLibraryItem } from './types'

export const PROMPT_LIBRARY: PromptLibraryItem[] = [
  { key: 'icebreakers-first-impression', question: 'Be honest: what did you think of me before you actually knew me?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], mood: 'juicy', about: 'me' },
  { key: 'icebreakers-three-truths', question: 'Which one of these is the lie?', category: 'icebreakers', personas: ['lifestyle', 'creator'], responseFormat: 'choice', options: ['I’ve never been on a plane', 'I once got lost in a market for 3 hours', 'I can’t swim'], correctOptionIndex: 0, mood: 'fun', about: 'me' },
  { key: 'icebreakers-compliment', question: 'What is something about me you genuinely respect but have never said?', category: 'icebreakers', personas: ['mentor', 'lifestyle'], mood: 'emotional', about: 'me' },
  { key: 'icebreakers-nickname', question: 'If you had to give me a nickname based on my personality, what would it be?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'me' },
  { key: 'icebreakers-secondary-school-did', question: 'Which of these did I actually do in secondary school?', category: 'icebreakers', personas: ['lifestyle', 'creator', 'student'], responseFormat: 'choice', options: ['Jumped the school fence to buy suya', 'Got flogged in front of the whole assembly', 'Wrote love letters for other people', 'Never got caught for anything, ever'], correctOptionIndex: 0, mood: 'nostalgic', about: 'me' },
  { key: 'icebreakers-red-flag', question: 'What harmless red flag do you think I probably have?', category: 'icebreakers', personas: ['relationships', 'young-adult'], mood: 'juicy', about: 'me' },

  { key: 'icebreakers-hidden-trait', question: 'What is one thing about me that surprised you after you got to know me?', category: 'icebreakers', personas: ['lifestyle', 'creator'], mood: 'emotional', about: 'me' },
  { key: 'icebreakers-owambe-me', question: 'If we went to an owambe together, what do you think I would do first?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], responseFormat: 'choice', options: ['Find food', 'Find the dance floor', 'Find a quiet corner', 'Start taking pictures'], correctOptionIndex: 0, mood: 'fun', about: 'me' },
  { key: 'icebreakers-marriage-auntie', question: 'If an auntie asked you why I am still single, what would you tell her?', category: 'icebreakers', personas: ['relationships', 'family'], mood: 'juicy', about: 'me' },
  { key: 'icebreakers-memory', question: 'What is the first memory of me that comes to your mind?', category: 'icebreakers', personas: ['lifestyle', 'family'], mood: 'nostalgic', about: 'me' },
  { key: 'icebreakers-most-likely', question: 'What do you think I am most likely to get famous for?', category: 'icebreakers', personas: ['creator', 'founder'], mood: 'fun', about: 'me' },
  { key: 'icebreakers-real-me', question: 'What do you think people misunderstand about me?', category: 'icebreakers', personas: ['lifestyle', 'mentor'], mood: 'emotional', about: 'me' },

  { key: 'icebreakers-never-have-i-ever', question: 'Which of these have I actually never done?', category: 'icebreakers', personas: ['lifestyle', 'creator'], responseFormat: 'choice', options: ['Eaten amala', 'Missed a flight', 'Cried during a movie', 'Pulled an all-nighter'], correctOptionIndex: 0, mood: 'fun', about: 'me' },
  { key: 'icebreakers-wrong-assumption', question: 'What is the funniest wrong assumption you have ever made about me?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], mood: 'juicy', about: 'me' },
  { key: 'icebreakers-green-flag', question: 'What is my biggest green flag from what you know about me?', category: 'icebreakers', personas: ['relationships', 'lifestyle'], mood: 'emotional', about: 'me' },
  { key: 'icebreakers-kid-dream-job', question: 'What did I want to be when I was a kid?', category: 'icebreakers', personas: ['lifestyle', 'creator'], responseFormat: 'choice', options: ['A pilot', 'A doctor, because my parents said so', 'A musician', 'Rich. That was the whole plan'], correctOptionIndex: 0, mood: 'nostalgic', about: 'me' },
  { key: 'icebreakers-secret-opinion', question: 'What opinion do you think I probably have but rarely say out loud?', category: 'icebreakers', personas: ['lifestyle', 'creator'], mood: 'juicy', about: 'me' },
  { key: 'icebreakers-secret-talent', question: 'What random talent do you think I secretly have?', category: 'icebreakers', personas: ['creator', 'lifestyle'], mood: 'fun', about: 'me' },

  { key: 'icebreakers-real-guilty-pleasure', question: 'Which of these is my real guilty pleasure?', category: 'icebreakers', personas: ['lifestyle', 'creator'], responseFormat: 'choice', options: ['Rewatching the same series for the fifth time', 'Indomie at 2am, no matter what', 'Scrolling old classmates’ pictures', 'Singing loudly when nobody’s home'], correctOptionIndex: 0, mood: 'fun', about: 'me' },
  { key: 'icebreakers-best-quality', question: 'What do you think is my best quality from the little you know?', category: 'icebreakers', personas: ['lifestyle', 'mentor'], mood: 'emotional', about: 'me' },
  { key: 'icebreakers-chat-energy', question: 'What do you think my texting style says about me?', category: 'icebreakers', personas: ['lifestyle', 'relationships'], mood: 'juicy', about: 'me' },
  { key: 'icebreakers-broke-move', question: 'When I’m broke, what do I actually do?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], responseFormat: 'choice', options: ['Survive on garri and groundnut', 'Suddenly start “fasting”', 'Ask for a small loan I’ll pay back soon', 'Still order food, then panic'], correctOptionIndex: 0, mood: 'fun', about: 'me' },
  { key: 'icebreakers-gist-worthy', question: 'What is one thing about me you think would make a good gist?', category: 'icebreakers', personas: ['lifestyle', 'creator'], mood: 'juicy', about: 'me' },
  { key: 'icebreakers-village-people', question: 'What everyday situation would probably make me blame village people?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'me' },

  { key: 'icebreakers-biggest-fear', question: 'Which of these am I actually scared of?', category: 'icebreakers', personas: ['lifestyle', 'creator'], responseFormat: 'choice', options: ['Cockroaches that fly', 'Deep water', 'Light going off right before a movie ends', 'Speaking in front of a crowd'], correctOptionIndex: 0, mood: 'fun', about: 'me' },
  { key: 'icebreakers-trip-companion', question: 'Would I be a good travel partner? Tell me why or why not.', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], mood: 'juicy', about: 'me' },
  { key: 'icebreakers-first-date-vibe', question: 'If you met me for the first time today, what would you assume I do for a living?', category: 'icebreakers', personas: ['career', 'young-adult'], mood: 'fun', about: 'me' },
  { key: 'icebreakers-reply-speed', question: 'Be honest: how fast do I really reply to messages?', category: 'icebreakers', personas: ['lifestyle', 'relationships'], responseFormat: 'choice', options: ['Instantly, I’m always online', 'A few hours. I saw it though', 'Days later. I forgot', 'I replied in my head'], correctOptionIndex: 0, mood: 'juicy', about: 'me' },
  { key: 'icebreakers-wrong-career', question: 'What career do you think I would be terrible at?', category: 'icebreakers', personas: ['career', 'young-adult'], mood: 'fun', about: 'me' },
  { key: 'icebreakers-what-would-i-do', question: 'If something embarrassing happened in public, how do you think I would react?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'me' },

  { key: 'icebreakers-million-first', question: 'If I got ₦1 million right now, what would I do first?', category: 'icebreakers', personas: ['lifestyle', 'finance'], responseFormat: 'choice', options: ['Clear everything I owe', 'Take everyone out', 'Save it and tell nobody', 'Book a flight immediately'], correctOptionIndex: 0, mood: 'fun', about: 'me' },
  { key: 'icebreakers-detty-december', question: 'If I landed in Lagos for Detty December, what would you expect me to spend money on first?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'me' },
  { key: 'icebreakers-survival', question: 'If we were stranded somewhere for 24 hours, what job would you trust me with?', category: 'icebreakers', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'me' },
  { key: 'icebreakers-first-message', question: 'If you had to start a conversation with me using one question, what would you ask?', category: 'icebreakers', personas: ['lifestyle', 'relationships'], mood: 'fun', about: 'me' },

  { key: 'love-unpopular-opinion', question: 'What is your most unpopular opinion about modern dating?', category: 'love', personas: ['relationships', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'love-green-flag', question: 'What small thing makes you think, ‘Okay, this person is different’?', category: 'love', personas: ['relationships'], mood: 'emotional', about: 'you' },
  { key: 'love-first-date-story', question: 'What is the funniest thing that has happened on a first date?', category: 'love', personas: ['relationships'], mood: 'fun', about: 'you' },
  { key: 'love-first-date-payer', question: 'Be honest: on a first date, who should pay?', category: 'love', personas: ['relationships', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'love-still-think', question: 'What kind of person do you think you would still remember years later?', category: 'love', personas: ['relationships'], mood: 'nostalgic', about: 'you' },
  { key: 'love-love-language', question: 'What is something simple someone can do that makes you feel genuinely cared for?', category: 'love', personas: ['relationships'], mood: 'emotional', about: 'you' },

  { key: 'love-texting-change', question: 'What texting habit instantly tells you someone is losing interest?', category: 'love', personas: ['relationships', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'love-auntie-question', question: 'What relationship question from Nigerian aunties secretly stresses you out?', category: 'love', personas: ['relationships', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'love-soft-spot', question: 'What kind of person can easily get you emotionally attached?', category: 'love', personas: ['relationships'], mood: 'emotional', about: 'you' },
  { key: 'love-friend-zone', question: 'Can two people genuinely stay friends after one catches feelings?', category: 'love', personas: ['relationships'], mood: 'juicy', about: 'you' },
  { key: 'love-unexpected-crush', question: 'Have you ever developed a crush on someone you never expected to like?', category: 'love', personas: ['relationships'], mood: 'nostalgic', about: 'you' },
  { key: 'love-dry-season', question: 'What is the longest you have gone without seriously liking anyone?', category: 'love', personas: ['relationships', 'young-adult'], mood: 'fun', about: 'you' },

  { key: 'love-early-warning', question: 'What is a dating red flag people ignore because the person is attractive?', category: 'love', personas: ['relationships'], mood: 'juicy', about: 'you' },
  { key: 'love-relationship-advice', question: 'What relationship advice did you learn only after making the mistake yourself?', category: 'love', personas: ['relationships', 'mentor'], mood: 'emotional', about: 'you' },
  { key: 'love-love-or-peace', question: 'Would you rather have intense chemistry or calm consistency?', category: 'love', personas: ['relationships', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'love-almost-relationship', question: 'What is the biggest reason an ‘almost relationship’ stays almost?', category: 'love', personas: ['relationships'], mood: 'emotional', about: 'you' },
  { key: 'love-secret-sign', question: 'What is your personal sign that you are starting to fall for someone?', category: 'love', personas: ['relationships'], mood: 'juicy', about: 'you' },
  { key: 'love-second-chance', question: 'What would make you seriously consider giving an ex another chance?', category: 'love', personas: ['relationships'], mood: 'juicy', about: 'you' },

  { key: 'love-first-move', question: 'What is one thing that can make you lose interest even when you initially liked someone?', category: 'love', personas: ['relationships', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'love-long-distance', question: 'What makes long-distance relationships harder than people admit?', category: 'love', personas: ['relationships'], mood: 'emotional', about: 'you' },

  { key: 'family-auntie-marriage', question: 'What is the funniest marriage pressure line an auntie has ever given you?', category: 'family', personas: ['family', 'relationships'], mood: 'fun', about: 'you' },
  { key: 'family-parent-phrase', question: 'What sentence did your parents say so often that you can hear their voice saying it?', category: 'family', personas: ['family'], mood: 'nostalgic', about: 'you' },
  { key: 'family-favourite-child', question: 'Be honest: what makes you suspect there is a favourite child in your family?', category: 'family', personas: ['family', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'family-best-family-memory', question: 'What ordinary family moment do you wish you could experience one more time?', category: 'family', personas: ['family'], mood: 'nostalgic', about: 'you' },
  { key: 'family-black-tax', question: 'What is the most unexpected thing your family has ever expected you to pay for?', category: 'family', personas: ['family', 'young-adult', 'finance'], mood: 'fun', about: 'you' },
  { key: 'family-family-expectation', question: 'What family expectation took you the longest to realize was not actually your responsibility?', category: 'family', personas: ['family', 'wellbeing'], mood: 'emotional', about: 'you' },

  { key: 'family-childhood-rule', question: 'What childhood rule in your house made absolutely no sense?', category: 'family', personas: ['family', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'family-sibling-gist', question: 'What is one harmless thing your sibling could spill about you in five seconds?', category: 'family', personas: ['family', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'family-family-advice', question: 'What advice from an older relative turned out to be surprisingly true?', category: 'family', personas: ['family', 'mentor'], mood: 'emotional', about: 'you' },
  { key: 'family-village-visit', question: 'What is one thing that always happens when you visit the village?', category: 'family', personas: ['family', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'family-home-sound', question: 'What sound instantly takes you back to your childhood home?', category: 'family', personas: ['family'], mood: 'nostalgic', about: 'you' },
  { key: 'family-money-home', question: 'At what point should an adult child stop being financially responsible for everyone at home?', category: 'family', personas: ['family', 'finance'], mood: 'juicy', about: 'you' },

  { key: 'family-household-job', question: 'What household chore did you hate the most growing up?', category: 'family', personas: ['family', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'family-family-secret', question: 'What harmless family secret did you discover when you got older?', category: 'family', personas: ['family'], mood: 'juicy', about: 'you' },
  { key: 'family-homecoming', question: 'What is the first thing your family notices when you come home after a long time away?', category: 'family', personas: ['family'], mood: 'nostalgic', about: 'you' },
  { key: 'family-adulting-warning', question: 'What part of becoming an adult did your family completely fail to prepare you for?', category: 'family', personas: ['family', 'young-adult'], mood: 'emotional', about: 'you' },
  { key: 'family-family-group-chat', question: 'What kind of message can make you immediately open your family group chat?', category: 'family', personas: ['family', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'family-home-food', question: 'What food did your family make so often that you got tired of it?', category: 'family', personas: ['family', 'young-adult'], mood: 'nostalgic', about: 'you' },

  { key: 'family-parent-money', question: 'What money lesson from your parents still influences how you spend today?', category: 'family', personas: ['family', 'finance'], mood: 'emotional', about: 'you' },
  { key: 'family-younger-self', question: 'What is something your younger self believed about family that you no longer believe?', category: 'family', personas: ['family', 'wellbeing'], mood: 'nostalgic', about: 'you' },

  { key: 'campus-asuu-strike', question: 'What did you actually do during the longest ASUU strike you experienced?', category: 'campus', personas: ['campus', 'student', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'campus-crush', question: 'Did you ever have a campus crush you never told?', category: 'campus', personas: ['campus', 'relationships'], mood: 'juicy', about: 'you' },
  { key: 'campus-first-day', question: 'What is the first thing you remember about your first day on campus?', category: 'campus', personas: ['campus', 'student'], mood: 'nostalgic', about: 'you' },
  { key: 'campus-lecturer-story', question: 'What is the funniest thing a lecturer has ever said in class?', category: 'campus', personas: ['campus', 'student'], mood: 'fun', about: 'you' },
  { key: 'campus-school-regret', question: 'What is something you wish someone had warned you about before university?', category: 'campus', personas: ['campus', 'student', 'mentor'], mood: 'emotional', about: 'you' },
  { key: 'campus-exam-night', question: 'What is your most unbelievable last-minute exam preparation story?', category: 'campus', personas: ['campus', 'student'], mood: 'juicy', about: 'you' },

  { key: 'campus-school-food', question: 'What was your go-to cheap meal when money was tight on campus?', category: 'campus', personas: ['campus', 'student', 'finance'], mood: 'nostalgic', about: 'you' },
  { key: 'campus-class-skip', question: 'What was your most creative excuse for missing a class?', category: 'campus', personas: ['campus', 'student'], mood: 'fun', about: 'you' },
  { key: 'campus-friendship', question: 'What is one thing your closest school friend did that you still remember?', category: 'campus', personas: ['campus', 'student'], mood: 'emotional', about: 'you' },
  { key: 'campus-course-regret', question: 'What course did you choose that you would absolutely not choose again?', category: 'campus', personas: ['campus', 'student'], mood: 'juicy', about: 'you' },
  { key: 'campus-hostel-life', question: 'What is one hostel experience you will never forget?', category: 'campus', personas: ['campus', 'student'], mood: 'nostalgic', about: 'you' },
  { key: 'campus-danfo-to-class', question: 'What is the most chaotic journey you have ever made just to get to class?', category: 'campus', personas: ['campus', 'student'], mood: 'fun', about: 'you' },

  { key: 'campus-japa-plan', question: 'When did you first seriously think, ‘I might actually japa’?', category: 'campus', personas: ['campus', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'campus-result-day', question: 'What did you do the moment you saw a result you were happy with?', category: 'campus', personas: ['campus', 'student'], mood: 'emotional', about: 'you' },
  { key: 'campus-best-memory', question: 'What random campus memory can still make you laugh years later?', category: 'campus', personas: ['campus', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'campus-project-night', question: 'What is the craziest group-project experience you have had?', category: 'campus', personas: ['campus', 'student'], mood: 'fun', about: 'you' },
  { key: 'campus-graduation-feeling', question: 'What did graduation feel like after everything you went through?', category: 'campus', personas: ['campus', 'young-adult'], mood: 'emotional', about: 'you' },
  { key: 'campus-school-money', question: 'What is the most ridiculous thing you had to budget for as a student?', category: 'campus', personas: ['campus', 'student', 'finance'], mood: 'fun', about: 'you' },

  { key: 'campus-school-struggle', question: 'What part of university life was harder than you expected?', category: 'campus', personas: ['campus', 'student'], mood: 'emotional', about: 'you' },
  { key: 'campus-young-self', question: 'What would your first-year university self be shocked to know about you now?', category: 'campus', personas: ['campus', 'young-adult'], mood: 'nostalgic', about: 'you' },

  { key: 'work-interview-fail', question: 'What is the most awkward thing that has happened to you in an interview?', category: 'work', personas: ['career', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'work-quit-thought', question: 'What was the moment you seriously thought, ‘I need to leave this job’?', category: 'work', personas: ['career', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'work-manager-memory', question: 'What is something a manager once said that you still remember?', category: 'work', personas: ['career', 'hr'], mood: 'nostalgic', about: 'you' },
  { key: 'work-promotion', question: 'What achievement at work made you quietly proud of yourself?', category: 'work', personas: ['career'], mood: 'emotional', about: 'you' },
  { key: 'work-underpaid', question: 'When did you first realize you were probably being underpaid?', category: 'work', personas: ['career', 'finance'], mood: 'juicy', about: 'you' },
  { key: 'work-work-from-home', question: 'What is your most embarrassing work-from-home moment?', category: 'work', personas: ['career', 'young-adult'], mood: 'fun', about: 'you' },

  { key: 'work-first-job', question: 'What is one thing your first job taught you that school never did?', category: 'work', personas: ['career', 'young-adult'], mood: 'emotional', about: 'you' },
  { key: 'work-office-gist', question: 'What harmless office gist could you never forget?', category: 'work', personas: ['career', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'work-toxic-sign', question: 'What workplace red flag do you now recognize immediately?', category: 'work', personas: ['career', 'hr'], mood: 'juicy', about: 'you' },
  { key: 'work-nigeria-salary', question: 'What salary sounded huge when you were younger but feels different now?', category: 'work', personas: ['career', 'young-adult', 'finance'], mood: 'nostalgic', about: 'you' },
  { key: 'work-career-advice', question: 'What career advice sounded wrong at first but turned out to be true?', category: 'work', personas: ['career', 'mentor'], mood: 'emotional', about: 'you' },
  { key: 'work-japa-career', question: 'What would make you seriously consider leaving Nigeria for a job?', category: 'work', personas: ['career', 'young-adult'], mood: 'juicy', about: 'you' },

  { key: 'work-office-food', question: 'What is the unofficial office food everyone somehow ends up sharing?', category: 'work', personas: ['career', 'lifestyle'], mood: 'fun', about: 'you' },
  { key: 'work-workplace-friend', question: 'How did a colleague become someone you genuinely trust?', category: 'work', personas: ['career'], mood: 'emotional', about: 'you' },
  { key: 'work-employee-unwritten-rule', question: 'What workplace rule did nobody tell you but you eventually learned?', category: 'work', personas: ['career', 'hr'], mood: 'juicy', about: 'you' },
  { key: 'work-career-switch', question: 'What career path would you choose if you could restart from zero?', category: 'work', personas: ['career', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'work-burnout-warning', question: 'What is the first sign that tells you you are getting burned out?', category: 'work', personas: ['career', 'wellbeing'], mood: 'emotional', about: 'you' },
  { key: 'work-boss-lesson', question: 'What is one lesson you learned from having a difficult boss?', category: 'work', personas: ['career', 'mentor'], mood: 'emotional', about: 'you' },

  { key: 'work-favourite-workday', question: 'What makes you finish a workday thinking, ‘Today was actually good’?', category: 'work', personas: ['career', 'wellbeing'], mood: 'emotional', about: 'you' },
  { key: 'work-job-memory', question: 'What is one ordinary workday you wish you could experience again?', category: 'work', personas: ['career'], mood: 'nostalgic', about: 'you' },

  { key: 'money-japa-money', question: 'If you got ₦10 million today, what would you do first?', category: 'money', personas: ['finance', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'money-black-tax', question: 'What is the most surprising ‘black tax’ expense you have ever had?', category: 'money', personas: ['finance', 'family', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'money-first-big-money', question: 'What is the first thing you remember buying when you finally had your own money?', category: 'money', personas: ['finance', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'money-regret', question: 'What is one money decision you wish you could undo?', category: 'money', personas: ['finance'], mood: 'emotional', about: 'you' },
  { key: 'money-detty-december-budget', question: 'What usually destroys your Detty December budget?', category: 'money', personas: ['finance', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'money-salary-secret', question: 'Should friends tell each other exactly how much they earn?', category: 'money', personas: ['finance', 'career'], mood: 'juicy', about: 'you' },

  { key: 'money-rich-feeling', question: 'What small thing makes you feel rich even when you are not?', category: 'money', personas: ['finance', 'lifestyle'], mood: 'fun', about: 'you' },
  { key: 'money-money-lie', question: 'What money lie did you believe for way too long?', category: 'money', personas: ['finance', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'money-childhood-money', question: 'What did you think rich people could afford when you were a child?', category: 'money', personas: ['finance', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'money-money-advice', question: 'What money advice do you wish you had learned at 18?', category: 'money', personas: ['finance', 'mentor'], mood: 'emotional', about: 'you' },
  { key: 'money-fastest-spend', question: 'What is the fastest you have ever spent money after receiving it?', category: 'money', personas: ['finance', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'money-family-request', question: 'What is the most unexpected money request you have received from family?', category: 'money', personas: ['finance', 'family'], mood: 'juicy', about: 'you' },

  { key: 'money-worst-purchase', question: 'What is the most unnecessary thing you have spent serious money on?', category: 'money', personas: ['finance', 'lifestyle'], mood: 'fun', about: 'you' },
  { key: 'money-first-salary', question: 'What did you do with your first real salary?', category: 'money', personas: ['finance', 'career', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'money-debt-lesson', question: 'What did owing money teach you that saving money never could?', category: 'money', personas: ['finance'], mood: 'emotional', about: 'you' },
  { key: 'money-spending-trigger', question: 'What kind of purchase is hardest for you to resist?', category: 'money', personas: ['finance', 'lifestyle'], mood: 'fun', about: 'you' },
  { key: 'money-emergency', question: 'What is the most random thing you have had to spend emergency money on?', category: 'money', personas: ['finance', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'money-financial-freedom', question: 'What does ‘financial freedom’ actually mean to you personally?', category: 'money', personas: ['finance', 'young-adult'], mood: 'emotional', about: 'you' },

  { key: 'money-saving-habit', question: 'What money habit has genuinely helped you save more?', category: 'money', personas: ['finance'], mood: 'emotional', about: 'you' },
  { key: 'money-money-memory', question: 'What is the first money-related memory you can clearly remember?', category: 'money', personas: ['finance', 'family'], mood: 'nostalgic', about: 'you' },

  { key: 'general-village-people', question: 'What is one perfectly normal problem you have blamed on village people?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'general-unsent-message', question: 'What is something you have wanted to say to someone but never sent?', category: 'general', personas: ['relationships', 'wellbeing'], mood: 'emotional', about: 'you' },
  { key: 'general-jollof-truth', question: 'Be honest: what is one popular Nigerian food you do not actually like?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'juicy', about: 'you' },
  { key: 'general-childhood-dream', question: 'What did you swear you would become when you were a child?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'general-lagos-traffic', question: 'What is the wildest thing Lagos traffic has ever made you do?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'general-quiet-flex', question: 'What is something you can do now that younger you would be proud of?', category: 'general', personas: ['lifestyle', 'wellbeing'], mood: 'emotional', about: 'you' },

  { key: 'general-unpopular-opinion', question: 'What harmless opinion would you defend even if everyone disagrees?', category: 'general', personas: ['lifestyle', 'creator'], mood: 'juicy', about: 'you' },
  { key: 'general-embarrassing-memory', question: 'What harmless embarrassing moment still randomly comes back to you?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'general-random-flex', question: 'What completely unnecessary skill are you weirdly good at?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'general-people-pleasing', question: 'What is one thing you stopped doing because you realized you were only trying to please people?', category: 'general', personas: ['wellbeing', 'young-adult'], mood: 'emotional', about: 'you' },
  { key: 'general-dream-trip', question: 'If money and work were not a problem, where would you go tomorrow?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'general-old-friend', question: 'What is something you still remember about a friend you no longer talk to?', category: 'general', personas: ['lifestyle', 'relationships'], mood: 'nostalgic', about: 'you' },

  { key: 'general-phone-check', question: 'What is the first app you open when you pick up your phone?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'general-life-lesson', question: 'What lesson did life teach you the hard way?', category: 'general', personas: ['mentor', 'wellbeing'], mood: 'emotional', about: 'you' },
  { key: 'general-comfort-food', question: 'What food can fix your mood faster than almost anything?', category: 'general', personas: ['lifestyle', 'wellbeing'], mood: 'fun', about: 'you' },
  { key: 'general-thing-you-miss', question: 'What is something from your past you did not appreciate until it was gone?', category: 'general', personas: ['wellbeing', 'young-adult'], mood: 'nostalgic', about: 'you' },
  { key: 'general-social-battery', question: 'What is the fastest way to drain your social battery?', category: 'general', personas: ['lifestyle', 'wellbeing'], mood: 'fun', about: 'you' },
  { key: 'general-small-win', question: 'What tiny win can instantly improve your whole day?', category: 'general', personas: ['wellbeing', 'lifestyle'], mood: 'emotional', about: 'you' },

  { key: 'general-free-weekend', question: 'If you had a completely free weekend and unlimited data, what would you do?', category: 'general', personas: ['lifestyle', 'young-adult'], mood: 'fun', about: 'you' },
  { key: 'general-ordinary-memory', question: 'What ordinary day from your past would you happily relive?', category: 'general', personas: ['lifestyle', 'wellbeing'], mood: 'nostalgic', about: 'you' },
]

export const getLibraryPrompt = (key: string | null | undefined) =>
  PROMPT_LIBRARY.find((prompt) => prompt.key === key) ?? null
