/**
 * Seed Trigger API — Lightweight endpoint called by the feed page
 * to process any due scheduled seed content.
 *
 * This is the "page-load trigger" — fires in the background
 * when users visit the feed, processing due seed items.
 */

import { NextResponse } from 'next/server';
import { checkAndGenerateIfNeeded, processScheduledQueue } from '@/lib/seeding/seed-orchestrator';
import { supabaseAdmin } from '@/lib/core/supabase/admin-client';

export async function GET() {
  try {
    // Quick check: is seeding active?
    const { data: config } = await supabaseAdmin
      .from('seed_config')
      .select('is_active')
      .eq('id', 1)
      .single();

    if (!config?.is_active) {
      return NextResponse.json({ skipped: true, reason: 'inactive' });
    }

    // Auto-generate a new batch if existing threads are expiring or the feed is empty
    const genResult = await checkAndGenerateIfNeeded();

    // Process up to 10 due items
    const result = await processScheduledQueue(10);

    return NextResponse.json({ success: true, ...result, autoGenerated: genResult.generated, genReason: genResult.reason });
  } catch (err: any) {
    // Never return errors to prevent any debug info leakage
    console.error('[SeedTrigger] Error:', err);
    return NextResponse.json({ skipped: true });
  }
}
