import { NextRequest, NextResponse } from 'next/server';
import { checkAndGenerateIfNeeded, processScheduledQueue } from '@/lib/seeding/seed-orchestrator';
import { supabaseAdmin } from '@/lib/core/supabase/admin-client';

function isAuthorized(request: NextRequest): boolean {
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) return true;
  const bearer = request.headers.get('authorization');
  return request.headers.get('x-cron-secret') === cronSecret || bearer === `Bearer ${cronSecret}`;
}

async function run(request: NextRequest) {
  if (!isAuthorized(request)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const { data: config } = await supabaseAdmin
      .from('seed_config')
      .select('is_active')
      .eq('id', 1)
      .single();

    if (!config?.is_active) {
      return NextResponse.json({ skipped: true, reason: 'inactive' });
    }

    const genResult = await checkAndGenerateIfNeeded();
    const result = await processScheduledQueue(10);

    return NextResponse.json({ success: true, ...result, autoGenerated: genResult.generated, genReason: genResult.reason });
  } catch (err: unknown) {
    console.error('[SeedTrigger] Error:', err);
    return NextResponse.json({ skipped: true });
  }
}

export async function GET(request: NextRequest) {
  return run(request);
}

export async function POST(request: NextRequest) {
  return run(request);
}
