/**
 * Content Playbook — Thread & Reply Templates
 *
 * Following WhisprSpace Master Seeding rules:
 * - No survey-style questions
 * - Personal hooks, emotional triggers, conversational tone
 * - Titles: 8-16 words, scroll-stopping, incomplete, curious
 * - Descriptions: 4-7 sentences, brief situation + emotional tension + open ending
 * - Replies: 3+ per thread, different tones, 1-3 sentences each
 */

export interface PlaybookThread {
  title: string;
  content: string;
  category: string;
  type: 'text' | 'poll';
  pollOptions?: string[];
  creatorPersona: string;
  replies: PlaybookReply[];
}

export interface PlaybookReply {
  personaTag: string;
  content: string;
  sequenceOrder: number;
  replyToSequence?: number;
}

// ─── GENERAL / CONFESSIONS ───────────────────────────────────
const generalThreads: PlaybookThread[] = [
  {
    title: 'I accidentally read a message that wasn\'t meant for me',
    content: 'I borrowed a friend\'s phone earlier and a notification popped up while I was using it. I shouldn\'t have opened it… but curiosity got the better of me. The message was them talking about me, and not in the way I expected. Now I\'m stuck wondering if I should confront them or just pretend I never saw it.',
    category: 'general',
    type: 'text',
    creatorPersona: 'storyteller',
    replies: [
      { personaTag: 'advisor', content: 'Been in almost the exact same situation. It\'s honestly one of the worst feelings — knowing something you can\'t unknow.', sequenceOrder: 1 },
      { personaTag: 'realist', content: 'Sometimes it\'s better not to confront people about things you accidentally see. You\'ll just have to explain how you found out.', sequenceOrder: 2 },
      { personaTag: 'curious_one', content: 'Now I\'m curious… was it negative or just unexpected? Because those hit very differently.', sequenceOrder: 3 },
      { personaTag: 'deep_thinker', content: 'The real question is — would you rather know the truth and feel hurt, or live in blissful ignorance?', sequenceOrder: 4, replyToSequence: 1 },
      { personaTag: 'funny_one', content: 'This is exactly why I never let anyone touch my phone. Not because I have secrets, just anxiety lol', sequenceOrder: 5 },
      { personaTag: 'poet', content: 'There is a quiet tragedy in this shared human experience.', sequenceOrder: 6 },
      { personaTag: 'tech_enthusiast', content: 'There\'s probably an app that tracks this kind of behavior.', sequenceOrder: 7 },
      { personaTag: 'optimist', content: 'This is just a bump in the road! Things will definitely get better.', sequenceOrder: 8 },
      { personaTag: 'wellness_advocate', content: 'This is why daily mindfulness is so important.', sequenceOrder: 9 },
      { personaTag: 'peacemaker', content: 'Give yourself some grace. We\'re all just figuring it out.', sequenceOrder: 10 },
      { personaTag: 'curious_one', content: 'I wonder how differently this would play out 50 years ago?', sequenceOrder: 11 },
      { personaTag: 'wise_beyond_years', content: 'Time has a way of smoothing out these sharp edges.', sequenceOrder: 12 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 13 },
      { personaTag: 'storyteller', content: 'Reminds me of a time in college when everything went exactly like this.', sequenceOrder: 14 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'Everyone thinks I have my life together but honestly I\'m completely lost',
    content: 'People keep telling me how proud they are of me and how well I\'m doing. Meanwhile I have no idea what I\'m doing with my career, my relationships feel surface-level, and I cry in the shower more often than I\'d admit. The gap between how people see me and how I actually feel is getting wider every day.',
    category: 'general',
    type: 'text',
    creatorPersona: 'night_owl',
    replies: [
      { personaTag: 'wellness_advocate', content: 'You just described what so many of us feel but never say out loud. You\'re not alone in this, I promise.', sequenceOrder: 1 },
      { personaTag: 'poet', content: 'We\'re all just wearing masks of competence while drowning quietly. The bravest thing you can do is take yours off — even here, anonymously.', sequenceOrder: 2 },
      { personaTag: 'realist', content: 'Hot take: nobody actually has their life together. Some people are just better at pretending.', sequenceOrder: 3 },
      { personaTag: 'optimist', content: 'The fact that you can recognize this means you\'re more self-aware than most. That\'s actually step one.', sequenceOrder: 4, replyToSequence: 1 },
      { personaTag: 'advisor', content: 'Have you tried talking to even one person honestly? Not asking for advice, just being real. It changes everything.', sequenceOrder: 5 },
      { personaTag: 'researcher', content: 'There are several studies that confirm this behavioral pattern.', sequenceOrder: 6 },
      { personaTag: 'contrarian', content: 'I actually completely disagree with the premise of this.', sequenceOrder: 7 },
      { personaTag: 'wise_beyond_years', content: 'Time has a way of smoothing out these sharp edges.', sequenceOrder: 8 },
      { personaTag: 'unfiltered', content: 'This is literally just life. Deal with it.', sequenceOrder: 9 },
      { personaTag: 'storyteller', content: 'Reminds me of a time in college when everything went exactly like this.', sequenceOrder: 10 },
      { personaTag: 'creative', content: 'This sounds like the opening scene of an indie movie.', sequenceOrder: 11 },
      { personaTag: 'poet', content: 'We are all just echoes trying to be heard in a very loud world.', sequenceOrder: 12 },
      { personaTag: 'provocateur', content: 'Honestly, this sounds like a consequence of your own actions.', sequenceOrder: 13 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 14 },
      { personaTag: 'advisor', content: 'Communication is key here. Just be honest about it.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I think my friend secretly resents me and I don\'t know what I did',
    content: 'We\'ve been close for years but lately the energy is just… off. Short replies, cancelled plans, and this passive-aggressive vibe I can\'t quite pin down. I\'ve tried asking if something\'s wrong and they just say "I\'m fine." But we all know what "I\'m fine" really means.',
    category: 'general',
    type: 'text',
    creatorPersona: 'creative',
    replies: [
      { personaTag: 'storyteller', content: 'I lost a 7-year friendship exactly like this. The slow fade is worse than a blowup because you never get closure.', sequenceOrder: 1 },
      { personaTag: 'contrarian', content: 'Or… maybe they\'re actually going through something that has nothing to do with you? We tend to make other people\'s problems about ourselves.', sequenceOrder: 2 },
      { personaTag: 'peacemaker', content: 'Maybe try a different approach — instead of asking "what\'s wrong," share something vulnerable first. It creates space for honesty.', sequenceOrder: 3 },
      { personaTag: 'skeptic', content: 'If someone says "I\'m fine" more than twice, they\'re either genuinely fine or they don\'t want to talk about it. Either way, pushing won\'t help.', sequenceOrder: 4, replyToSequence: 2 },
      { personaTag: 'unfiltered', content: 'Real talk: some friendships have expiry dates and that\'s okay. Not every connection is meant to last forever.', sequenceOrder: 5 },
      { personaTag: 'realist', content: 'It is what it is. You just have to deal with it and move forward.', sequenceOrder: 6 },
      { personaTag: 'creative', content: 'There\'s actually a strange beauty to experiencing this.', sequenceOrder: 7 },
      { personaTag: 'night_owl', content: 'This is the exact kind of thought that keeps me awake at night.', sequenceOrder: 8 },
      { personaTag: 'contrarian', content: 'Have you considered the exact opposite might be true?', sequenceOrder: 9 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 10 },
      { personaTag: 'deep_thinker', content: 'It\'s fascinating how our brains process these exact situations.', sequenceOrder: 11 },
      { personaTag: 'funny_one', content: 'This is why I just stay in bed with my snacks.', sequenceOrder: 12 },
      { personaTag: 'poet', content: 'Like rain on a windowpane, these moments wash over us and fade.', sequenceOrder: 13 },
      { personaTag: 'wellness_advocate', content: 'Protect your peace at all costs.', sequenceOrder: 14 },
      { personaTag: 'unfiltered', content: 'This is literally just life. Deal with it.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I pretended to be happy at a party and now I feel worse than before',
    content: 'Went to this gathering last night and spent the whole time laughing, dancing, being the "fun one." Got home, closed the door, and just sat on the floor for like twenty minutes. The performance is exhausting. Does anyone else feel like socializing drains them even when they look like they\'re loving it?',
    category: 'general',
    type: 'text',
    creatorPersona: 'night_owl',
    replies: [
      { personaTag: 'deep_thinker', content: 'The loneliest people are often the funniest at parties. There\'s actually research on this.', sequenceOrder: 1 },
      { personaTag: 'wellness_advocate', content: 'This is your social battery telling you something. It\'s okay to leave early or just not go. Your peace matters more than appearances.', sequenceOrder: 2 },
      { personaTag: 'funny_one', content: 'Me leaving a party: "that was so fun!" Me ten minutes later in bed staring at the ceiling: 👁👄👁', sequenceOrder: 3 },
      { personaTag: 'poet', content: 'There is a quiet tragedy in this shared human experience.', sequenceOrder: 4 },
      { personaTag: 'debater', content: 'I can argue both sides of this, but here\'s where your argument fails.', sequenceOrder: 5 },
      { personaTag: 'optimist', content: 'This is just a bump in the road! Things will definitely get better.', sequenceOrder: 6 },
      { personaTag: 'deep_thinker', content: 'It\'s fascinating how our brains process these exact situations.', sequenceOrder: 7 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 8 },
      { personaTag: 'wise_beyond_years', content: 'In ten years, you\'ll look back at this differently.', sequenceOrder: 9 },
      { personaTag: 'realist', content: 'Harsh truth: nobody is going to fix this for you.', sequenceOrder: 10 },
      { personaTag: 'researcher', content: 'There are several studies that confirm this behavioral pattern.', sequenceOrder: 11 },
      { personaTag: 'provocateur', content: 'Honestly, this sounds like a consequence of your own actions.', sequenceOrder: 12 },
      { personaTag: 'unfiltered', content: 'Stop making excuses and just deal with it.', sequenceOrder: 13 },
      { personaTag: 'tech_enthusiast', content: 'Digital minimalism might actually solve this for you.', sequenceOrder: 14 },
      { personaTag: 'curious_one', content: 'What do you think is the root cause of feeling this way?', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I lied about something years ago and it still eats at me',
    content: 'It wasn\'t even a big lie at the time. Just something I said to avoid an uncomfortable situation. But it snowballed and now the lie is basically baked into how certain people see me. If I come clean now it would change everything, but keeping it going is slowly killing me inside.',
    category: 'general',
    type: 'text',
    creatorPersona: 'poet',
    replies: [
      { personaTag: 'advisor', content: 'The weight of carrying a lie is almost always heavier than the consequences of telling the truth. Almost.', sequenceOrder: 1 },
      { personaTag: 'realist', content: 'Depends on the lie. Some truths don\'t need to come out if they\'d only hurt people and serve your guilt, not their wellbeing.', sequenceOrder: 2 },
      { personaTag: 'storyteller', content: 'I had a similar situation. Told the truth after 3 years. Lost a friend but gained my sanity. Would do it again.', sequenceOrder: 3 },
      { personaTag: 'contrarian', content: 'Counter-thought: maybe the person you\'ve become since the lie IS you. People change. The lie might not even matter anymore.', sequenceOrder: 4, replyToSequence: 1 },
      { personaTag: 'realist', content: 'It is what it is. You just have to deal with it and move forward.', sequenceOrder: 5 },
      { personaTag: 'provocateur', content: 'Maybe the uncomfortable truth is that you\'re the problem?', sequenceOrder: 6 },
      { personaTag: 'debater', content: 'Let\'s break down the logic of this situation piece by piece.', sequenceOrder: 7 },
      { personaTag: 'contrarian', content: 'I see it differently. The conventional wisdom is wrong here.', sequenceOrder: 8 },
      { personaTag: 'creative', content: 'There\'s actually a strange beauty to experiencing this.', sequenceOrder: 9 },
      { personaTag: 'deep_thinker', content: 'The underlying psychology here is something we rarely talk about.', sequenceOrder: 10 },
      { personaTag: 'optimist', content: 'Every challenge is just an opportunity to learn something new.', sequenceOrder: 11 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 12 },
      { personaTag: 'curious_one', content: 'Has anyone else noticed this trend recently or is it just me?', sequenceOrder: 13 },
      { personaTag: 'unfiltered', content: 'We really need to stop overthinking basic human interactions.', sequenceOrder: 14 },
      { personaTag: 'funny_one', content: 'My therapist is going to hear about this one.', sequenceOrder: 15 },
    ],
  },
];

// ─── TECH ────────────────────────────────────────────────────
const techThreads: PlaybookThread[] = [
  {
    title: 'I\'m mass deleting my social media accounts and honestly it feels terrifying',
    content: 'Started removing my accounts one by one this week — Instagram first, then Twitter. Facebook is next. The weird part isn\'t missing the content, it\'s this irrational fear that I\'ll somehow stop existing if I\'m not "online." Like, if there\'s no digital version of me, do I still matter? That thought alone tells me I need to do this.',
    category: 'tech',
    type: 'text',
    creatorPersona: 'deep_thinker',
    replies: [
      { personaTag: 'tech_enthusiast', content: 'Did this two years ago. First month was rough, genuine FOMO. After that? Best decision I ever made. My attention span came back.', sequenceOrder: 1 },
      { personaTag: 'skeptic', content: 'But you\'re literally posting on an anonymous platform about deleting social media. Isn\'t that still... social media?', sequenceOrder: 2 },
      { personaTag: 'funny_one', content: 'The fact that not having an Instagram feels "terrifying" is exactly why you should delete it lmao', sequenceOrder: 3 },
      { personaTag: 'optimist', content: 'The first week is the hardest. After that you start noticing how much time you actually have. You\'ll be shocked.', sequenceOrder: 4, replyToSequence: 1 },
      { personaTag: 'tech_enthusiast', content: 'There\'s probably an app that tracks this kind of behavior.', sequenceOrder: 5 },
      { personaTag: 'wellness_advocate', content: 'This is why daily mindfulness is so important.', sequenceOrder: 6 },
      { personaTag: 'provocateur', content: 'I\'m going to say what everyone is thinking: this was avoidable.', sequenceOrder: 7 },
      { personaTag: 'wise_beyond_years', content: 'The weight you\'re carrying will feel lighter as you age.', sequenceOrder: 8 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 9 },
      { personaTag: 'unfiltered', content: 'We really need to stop overthinking basic human interactions.', sequenceOrder: 10 },
      { personaTag: 'poet', content: 'We are all just echoes trying to be heard in a very loud world.', sequenceOrder: 11 },
      { personaTag: 'creative', content: 'There\'s actually a strange beauty to experiencing this.', sequenceOrder: 12 },
      { personaTag: 'advisor', content: 'Don\'t make any rash decisions while you\'re feeling this way.', sequenceOrder: 13 },
      { personaTag: 'skeptic', content: 'Sounds a bit exaggerated, but okay.', sequenceOrder: 14 },
      { personaTag: 'debater', content: 'Let\'s break down the logic of this situation piece by piece.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I think AI is going to take my job and nobody around me seems worried',
    content: 'I work in content writing and every week there\'s a new AI tool that does what I do but faster and cheaper. My coworkers keep saying "AI can\'t replace creativity" but honestly? The stuff it produces is good enough for most clients. I\'m genuinely scared and it feels like I\'m the only one paying attention.',
    category: 'tech',
    type: 'text',
    creatorPersona: 'realist',
    replies: [
      { personaTag: 'tech_enthusiast', content: 'The people who adapt and learn to work WITH AI will be fine. The ones who ignore it... yeah, that\'s gonna be rough.', sequenceOrder: 1 },
      { personaTag: 'contrarian', content: 'Every generation has had a "this will take our jobs" panic. ATMs didn\'t kill bank tellers. This feels similar.', sequenceOrder: 2 },
      { personaTag: 'unfiltered', content: 'I hate when people say "AI can\'t replace humans." It doesn\'t need to replace you perfectly. It just needs to be 80% as good at 10% of the cost.', sequenceOrder: 3 },
      { personaTag: 'researcher', content: 'McKinsey estimates 30% of work hours could be automated by 2030. The key word is "hours" not "jobs." Your role will change, not disappear.', sequenceOrder: 4, replyToSequence: 2 },
      { personaTag: 'advisor', content: 'Start learning how to use the tools instead of competing against them. Seriously. The best writers right now are AI-augmented.', sequenceOrder: 5 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 6 },
      { personaTag: 'wellness_advocate', content: 'Protect your peace at all costs.', sequenceOrder: 7 },
      { personaTag: 'skeptic', content: 'I\'d need more context before jumping to conclusions on this.', sequenceOrder: 8 },
      { personaTag: 'tech_enthusiast', content: 'There\'s probably an app that tracks this kind of behavior.', sequenceOrder: 9 },
      { personaTag: 'funny_one', content: 'This is why I just stay in bed with my snacks.', sequenceOrder: 10 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 11 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 12 },
      { personaTag: 'deep_thinker', content: 'It\'s fascinating how our brains process these exact situations.', sequenceOrder: 13 },
      { personaTag: 'realist', content: 'At the end of the day, you can only control your own actions.', sequenceOrder: 14 },
      { personaTag: 'curious_one', content: 'I wonder how differently this would play out 50 years ago?', sequenceOrder: 15 },
    ],
  },
  {
    title: 'My screen time report said 11 hours and I can\'t even argue with it',
    content: 'Got my weekly screen time notification and just stared at it. Eleven hours average per day. Between work, scrolling, and "just checking" my phone, I\'m basically living inside a screen. The worst part is I don\'t even enjoy most of it. It\'s just... habit.',
    category: 'tech',
    type: 'text',
    creatorPersona: 'night_owl',
    replies: [
      { personaTag: 'wellness_advocate', content: 'Try the 20-20-20 rule as a start. Every 20 minutes, look at something 20 feet away for 20 seconds. Small steps.', sequenceOrder: 1 },
      { personaTag: 'funny_one', content: 'My phone sent me a screen time report and I opened ANOTHER app to cope with the anxiety from reading it 💀', sequenceOrder: 2 },
      { personaTag: 'realist', content: 'If 7-8 of those hours are work, you\'re really only at 3-4 hours of recreational screen time. Context matters.', sequenceOrder: 3 },
      { personaTag: 'optimist', content: 'Every challenge is just an opportunity to learn something new.', sequenceOrder: 4 },
      { personaTag: 'unfiltered', content: 'We really need to stop overthinking basic human interactions.', sequenceOrder: 5 },
      { personaTag: 'wellness_advocate', content: 'This is why daily mindfulness is so important.', sequenceOrder: 6 },
      { personaTag: 'contrarian', content: 'I actually completely disagree with the premise of this.', sequenceOrder: 7 },
      { personaTag: 'realist', content: 'It is what it is. You just have to deal with it and move forward.', sequenceOrder: 8 },
      { personaTag: 'deep_thinker', content: 'This is a perfect example of how modern society shapes our internal dialogue.', sequenceOrder: 9 },
      { personaTag: 'funny_one', content: 'I\'m in this post and I don\'t like it lol', sequenceOrder: 10 },
      { personaTag: 'night_owl', content: 'Why do we only have these realizations when it\'s dark outside?', sequenceOrder: 11 },
      { personaTag: 'skeptic', content: 'I\'d need more context before jumping to conclusions on this.', sequenceOrder: 12 },
      { personaTag: 'tech_enthusiast', content: 'The algorithms definitely push these kinds of experiences.', sequenceOrder: 13 },
      { personaTag: 'researcher', content: 'There are several studies that confirm this behavioral pattern.', sequenceOrder: 14 },
      { personaTag: 'peacemaker', content: 'I think everyone involved is just doing their best.', sequenceOrder: 15 },
    ],
  },
];

// ─── LIFESTYLE ───────────────────────────────────────────────
const lifestyleThreads: PlaybookThread[] = [
  {
    title: 'I think adulthood is just people pretending to know what they\'re doing',
    content: 'I turned 27 last week and I still feel like I\'m winging everything. Bills, relationships, career decisions — I thought by now I\'d have some kind of manual. Turns out the manual doesn\'t exist and everyone is just making it up as they go. Is it just me or is this the biggest unspoken secret of being an adult?',
    category: 'lifestyle',
    type: 'text',
    creatorPersona: 'storyteller',
    replies: [
      { personaTag: 'wise_beyond_years', content: 'I\'m 34. Can confirm there\'s no manual. The only difference between 27 and 34 is that at 34 you stop feeling guilty about not knowing.', sequenceOrder: 1 },
      { personaTag: 'funny_one', content: 'I\'m 30 and I still google "how to adult" unironically at least once a month', sequenceOrder: 2 },
      { personaTag: 'deep_thinker', content: 'I think the real scam is that school taught us calculus but not how to handle existential dread or do taxes.', sequenceOrder: 3 },
      { personaTag: 'optimist', content: 'Plot twist: the fact that you\'re questioning it means you\'re more aware than most people who just go through the motions.', sequenceOrder: 4, replyToSequence: 1 },
      { personaTag: 'poet', content: 'We are all just echoes trying to be heard in a very loud world.', sequenceOrder: 5 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 6 },
      { personaTag: 'realist', content: 'At the end of the day, you can only control your own actions.', sequenceOrder: 7 },
      { personaTag: 'debater', content: 'You\'re relying on emotional reasoning rather than objective facts.', sequenceOrder: 8 },
      { personaTag: 'optimist', content: 'Every challenge is just an opportunity to learn something new.', sequenceOrder: 9 },
      { personaTag: 'deep_thinker', content: 'The underlying psychology here is something we rarely talk about.', sequenceOrder: 10 },
      { personaTag: 'advisor', content: 'The best thing you can do right now is take a step back and breathe.', sequenceOrder: 11 },
      { personaTag: 'wise_beyond_years', content: 'In ten years, you\'ll look back at this differently.', sequenceOrder: 12 },
      { personaTag: 'funny_one', content: 'My therapist is going to hear about this one.', sequenceOrder: 13 },
      { personaTag: 'contrarian', content: 'I see it differently. The conventional wisdom is wrong here.', sequenceOrder: 14 },
      { personaTag: 'peacemaker', content: 'Give yourself some grace. We\'re all just figuring it out.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I moved to a new city and the loneliness is hitting different',
    content: 'Everyone told me it would be exciting — fresh start, new opportunities. And it is, on paper. But nobody warned me about the quiet evenings, eating alone, and having nobody to call when something small but good happens. Making friends as an adult is genuinely one of the hardest things I\'ve ever had to do.',
    category: 'lifestyle',
    type: 'text',
    creatorPersona: 'poet',
    replies: [
      { personaTag: 'storyteller', content: 'Moved cities at 25. Took me almost a year to find my people. Hang in there — it gets better but it takes longer than you\'d think.', sequenceOrder: 1 },
      { personaTag: 'advisor', content: 'Try joining something regular — a gym class, a book club, anything with recurring faces. Friendship as an adult needs repeated exposure.', sequenceOrder: 2 },
      { personaTag: 'peacemaker', content: 'The "nobody to call when something small but good happens" part hits so hard. That\'s the real loneliness people don\'t talk about.', sequenceOrder: 3 },
      { personaTag: 'night_owl', content: 'I feel this deeply. Been in my new city for 6 months and my most meaningful conversations are with my Uber driver.', sequenceOrder: 4 },
      { personaTag: 'debater', content: 'Let\'s break down the logic of this situation piece by piece.', sequenceOrder: 5 },
      { personaTag: 'tech_enthusiast', content: 'There\'s probably an app that tracks this kind of behavior.', sequenceOrder: 6 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 7 },
      { personaTag: 'skeptic', content: 'I\'d need more context before jumping to conclusions on this.', sequenceOrder: 8 },
      { personaTag: 'wise_beyond_years', content: 'Time has a way of smoothing out these sharp edges.', sequenceOrder: 9 },
      { personaTag: 'advisor', content: 'Communication is key here. Just be honest about it.', sequenceOrder: 10 },
      { personaTag: 'realist', content: 'Harsh truth: nobody is going to fix this for you.', sequenceOrder: 11 },
      { personaTag: 'creative', content: 'This sounds like the opening scene of an indie movie.', sequenceOrder: 12 },
      { personaTag: 'storyteller', content: 'I had a scary similar experience a few years ago. It changes you.', sequenceOrder: 13 },
      { personaTag: 'unfiltered', content: 'We really need to stop overthinking basic human interactions.', sequenceOrder: 14 },
      { personaTag: 'poet', content: 'There is a quiet tragedy in this shared human experience.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I might have made the worst career decision of my life',
    content: 'Left a stable job to chase something I was passionate about. Three months in and I\'m burning through savings, the passion is starting to feel more like pressure, and everyone who said "follow your dreams" is suspiciously quiet now. Starting to wonder if stability was the dream all along.',
    category: 'lifestyle',
    type: 'text',
    creatorPersona: 'realist',
    replies: [
      { personaTag: 'contrarian', content: 'Three months is nothing. Most businesses and passion projects take 1-2 years to gain traction. You\'re still in the hard part.', sequenceOrder: 1 },
      { personaTag: 'researcher', content: 'Statistically, most people who quit stable jobs to pursue passion regret it... then 5 years later they\'re glad they did. It\'s a J-curve.', sequenceOrder: 2 },
      { personaTag: 'unfiltered', content: '"Follow your dreams" is advice from people who either got lucky or never actually tried it. Having a plan B isn\'t giving up.', sequenceOrder: 3 },
      { personaTag: 'curious_one', content: 'What do you think is the root cause of feeling this way?', sequenceOrder: 4 },
      { personaTag: 'creative', content: 'There\'s actually a strange beauty to experiencing this.', sequenceOrder: 5 },
      { personaTag: 'tech_enthusiast', content: 'Digital minimalism might actually solve this for you.', sequenceOrder: 6 },
      { personaTag: 'night_owl', content: 'This is the exact kind of thought that keeps me awake at night.', sequenceOrder: 7 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 8 },
      { personaTag: 'poet', content: 'We are all just echoes trying to be heard in a very loud world.', sequenceOrder: 9 },
      { personaTag: 'unfiltered', content: 'We really need to stop overthinking basic human interactions.', sequenceOrder: 10 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 11 },
      { personaTag: 'provocateur', content: 'Maybe the uncomfortable truth is that you\'re the problem?', sequenceOrder: 12 },
      { personaTag: 'contrarian', content: 'I see it differently. The conventional wisdom is wrong here.', sequenceOrder: 13 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 14 },
      { personaTag: 'advisor', content: 'The best thing you can do right now is take a step back and breathe.', sequenceOrder: 15 },
    ],
  },
];

// ─── ENTERTAINMENT ───────────────────────────────────────────
const entertainmentThreads: PlaybookThread[] = [
  {
    title: 'I tried to impress someone and it went catastrophically wrong',
    content: 'Was at a coffee shop and this person I\'d been wanting to talk to was right there. I walked over, tried to lean casually on the counter, and knocked over an entire display of mugs. Like, eight mugs just cascading to the floor one by one while I stood there frozen. They definitely saw. I definitely left.',
    category: 'entertainment',
    type: 'text',
    creatorPersona: 'funny_one',
    replies: [
      { personaTag: 'storyteller', content: 'This is the kind of story you tell at your wedding someday. Go back. Lean on the counter again. Assert dominance.', sequenceOrder: 1 },
      { personaTag: 'night_owl', content: 'The "one by one" part is sending me 😭 like each mug waited its turn to humiliate you', sequenceOrder: 2 },
      { personaTag: 'optimist', content: 'Honestly if someone isn\'t charmed by an adorable disaster like this, they\'re not your person anyway.', sequenceOrder: 3 },
      { personaTag: 'realist', content: 'I would simply never return to that coffee shop and find a new city to live in', sequenceOrder: 4 },
      { personaTag: 'researcher', content: 'There are several studies that confirm this behavioral pattern.', sequenceOrder: 5 },
      { personaTag: 'night_owl', content: 'Why do we only have these realizations when it\'s dark outside?', sequenceOrder: 6 },
      { personaTag: 'creative', content: 'This sounds like the opening scene of an indie movie.', sequenceOrder: 7 },
      { personaTag: 'wise_beyond_years', content: 'Time has a way of smoothing out these sharp edges.', sequenceOrder: 8 },
      { personaTag: 'advisor', content: 'Don\'t make any rash decisions while you\'re feeling this way.', sequenceOrder: 9 },
      { personaTag: 'curious_one', content: 'I wonder how differently this would play out 50 years ago?', sequenceOrder: 10 },
      { personaTag: 'skeptic', content: 'I\'d need more context before jumping to conclusions on this.', sequenceOrder: 11 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 12 },
      { personaTag: 'unfiltered', content: 'This is literally just life. Deal with it.', sequenceOrder: 13 },
      { personaTag: 'debater', content: 'You\'re relying on emotional reasoning rather than objective facts.', sequenceOrder: 14 },
      { personaTag: 'optimist', content: 'Every challenge is just an opportunity to learn something new.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I waved back at someone who absolutely was not waving at me',
    content: 'Walking through the mall and someone waved from across the way. I smiled, waved back enthusiastically. Big wave. They were waving at the person directly behind me. We made eye contact AFTER the wave. I committed to a full hand wave to nobody. The walk of shame to the nearest exit was the longest of my life.',
    category: 'entertainment',
    type: 'text',
    creatorPersona: 'storyteller',
    replies: [
      { personaTag: 'funny_one', content: 'The trick is to smoothly transition the wave into fixing your hair. Works 0% of the time but at least you tried.', sequenceOrder: 1 },
      { personaTag: 'peacemaker', content: 'This happens to literally everyone. The people who claim it hasn\'t happened to them are liars.', sequenceOrder: 2 },
      { personaTag: 'poet', content: 'We\'re all just waving at strangers hoping someone waves back. That\'s literally life.', sequenceOrder: 3 },
      { personaTag: 'unfiltered', content: 'We really need to stop overthinking basic human interactions.', sequenceOrder: 4 },
      { personaTag: 'wise_beyond_years', content: 'The weight you\'re carrying will feel lighter as you age.', sequenceOrder: 5 },
      { personaTag: 'skeptic', content: 'Sounds a bit exaggerated, but okay.', sequenceOrder: 6 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 7 },
      { personaTag: 'tech_enthusiast', content: 'There\'s probably an app that tracks this kind of behavior.', sequenceOrder: 8 },
      { personaTag: 'optimist', content: 'Every challenge is just an opportunity to learn something new.', sequenceOrder: 9 },
      { personaTag: 'debater', content: 'I can argue both sides of this, but here\'s where your argument fails.', sequenceOrder: 10 },
      { personaTag: 'contrarian', content: 'I actually completely disagree with the premise of this.', sequenceOrder: 11 },
      { personaTag: 'night_owl', content: 'This is the exact kind of thought that keeps me awake at night.', sequenceOrder: 12 },
      { personaTag: 'storyteller', content: 'This literally happened to a friend of mine. It took months to resolve.', sequenceOrder: 13 },
      { personaTag: 'peacemaker', content: 'I think everyone involved is just doing their best.', sequenceOrder: 14 },
      { personaTag: 'curious_one', content: 'I wonder how differently this would play out 50 years ago?', sequenceOrder: 15 },
    ],
  },
  {
    title: 'What show completely changed how you see the world?',
    content: 'Just finished watching something that left me staring at the ceiling for an hour processing it. Not going to say which one yet because I don\'t want to spoil it. But it genuinely made me rethink how I look at certain relationships in my life. Has a show or movie ever done that to you?',
    category: 'entertainment',
    type: 'text',
    creatorPersona: 'creative',
    replies: [
      { personaTag: 'deep_thinker', content: 'Black Mirror did this to me years ago. Some episodes I still think about randomly in the shower.', sequenceOrder: 1 },
      { personaTag: 'night_owl', content: 'Bojack Horseman. That show packaged depression into a cartoon horse and somehow made me understand myself better.', sequenceOrder: 2 },
      { personaTag: 'curious_one', content: 'Okay but you HAVE to tell us what you watched. You can\'t just drop this and not say which show!', sequenceOrder: 3 },
      { personaTag: 'wise_beyond_years', content: 'The weight you\'re carrying will feel lighter as you age.', sequenceOrder: 4 },
      { personaTag: 'curious_one', content: 'Has anyone else noticed this trend recently or is it just me?', sequenceOrder: 5 },
      { personaTag: 'skeptic', content: 'Sounds a bit exaggerated, but okay.', sequenceOrder: 6 },
      { personaTag: 'provocateur', content: 'Maybe the uncomfortable truth is that you\'re the problem?', sequenceOrder: 7 },
      { personaTag: 'unfiltered', content: 'This is literally just life. Deal with it.', sequenceOrder: 8 },
      { personaTag: 'peacemaker', content: 'Let\'s try to see it from all angles before getting upset.', sequenceOrder: 9 },
      { personaTag: 'researcher', content: 'There are several studies that confirm this behavioral pattern.', sequenceOrder: 10 },
      { personaTag: 'wellness_advocate', content: 'This is why daily mindfulness is so important.', sequenceOrder: 11 },
      { personaTag: 'realist', content: 'At the end of the day, you can only control your own actions.', sequenceOrder: 12 },
      { personaTag: 'advisor', content: 'The best thing you can do right now is take a step back and breathe.', sequenceOrder: 13 },
      { personaTag: 'funny_one', content: 'My therapist is going to hear about this one.', sequenceOrder: 14 },
      { personaTag: 'poet', content: 'There is a quiet tragedy in this shared human experience.', sequenceOrder: 15 },
    ],
  },
];

// ─── POLITICS ────────────────────────────────────────────────
const politicsThreads: PlaybookThread[] = [
  {
    title: 'I stopped watching the news and I genuinely feel better',
    content: 'Three weeks ago I stopped checking news apps, muted all news accounts, and stopped watching any news channel. My anxiety went down, I sleep better, and I feel less angry at strangers. But now I feel guilty — like I have a responsibility to stay informed. Is ignorance really bliss or am I just being irresponsible?',
    category: 'politics',
    type: 'text',
    creatorPersona: 'peacemaker',
    replies: [
      { personaTag: 'debater', content: 'There\'s a difference between being informed and being consumed. You can check news once a day without doomscrolling.', sequenceOrder: 1 },
      { personaTag: 'skeptic', content: 'Most "news" is designed to trigger your fight-or-flight response for clicks. Stepping back isn\'t ignorance, it\'s self-preservation.', sequenceOrder: 2 },
      { personaTag: 'provocateur', content: 'Unpopular opinion: if everyone stopped hate-watching the news, media companies would be forced to actually report facts instead of outrage.', sequenceOrder: 3 },
      { personaTag: 'debater', content: 'Let\'s break down the logic of this situation piece by piece.', sequenceOrder: 4 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 5 },
      { personaTag: 'creative', content: 'This sounds like the opening scene of an indie movie.', sequenceOrder: 6 },
      { personaTag: 'deep_thinker', content: 'It\'s fascinating how our brains process these exact situations.', sequenceOrder: 7 },
      { personaTag: 'funny_one', content: 'My therapist is going to hear about this one.', sequenceOrder: 8 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 9 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 10 },
      { personaTag: 'provocateur', content: 'Maybe the uncomfortable truth is that you\'re the problem?', sequenceOrder: 11 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 12 },
      { personaTag: 'contrarian', content: 'I actually completely disagree with the premise of this.', sequenceOrder: 13 },
      { personaTag: 'skeptic', content: 'Sounds a bit exaggerated, but okay.', sequenceOrder: 14 },
      { personaTag: 'curious_one', content: 'What do you think is the root cause of feeling this way?', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I think social media friendships are mostly performative',
    content: 'I\'ve got like 500 "friends" online. Birthday messages, likes on photos, the whole thing. But when I actually needed help last month — real, tangible help — exactly two people showed up. Two out of five hundred. It made me realize most of my online connections are just... noise.',
    category: 'politics',
    type: 'text',
    creatorPersona: 'unfiltered',
    replies: [
      { personaTag: 'researcher', content: 'Dunbar\'s number says we can only maintain about 150 meaningful relationships. Social media just made us think we beat that limit.', sequenceOrder: 1 },
      { personaTag: 'wise_beyond_years', content: 'Two people showed up. That\'s not a failure, that\'s your real circle. Most people would be lucky to have two.', sequenceOrder: 2 },
      { personaTag: 'contrarian', content: 'Maybe some of those 500 would have helped if they knew you needed it. Not everyone is a mindreader.', sequenceOrder: 3 },
      { personaTag: 'deep_thinker', content: 'This is a perfect example of how modern society shapes our internal dialogue.', sequenceOrder: 4 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 5 },
      { personaTag: 'funny_one', content: 'This is why I just stay in bed with my snacks.', sequenceOrder: 6 },
      { personaTag: 'provocateur', content: 'Maybe the uncomfortable truth is that you\'re the problem?', sequenceOrder: 7 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 8 },
      { personaTag: 'contrarian', content: 'I see it differently. The conventional wisdom is wrong here.', sequenceOrder: 9 },
      { personaTag: 'advisor', content: 'Communication is key here. Just be honest about it.', sequenceOrder: 10 },
      { personaTag: 'poet', content: 'There is a quiet tragedy in this shared human experience.', sequenceOrder: 11 },
      { personaTag: 'debater', content: 'You\'re relying on emotional reasoning rather than objective facts.', sequenceOrder: 12 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 13 },
      { personaTag: 'skeptic', content: 'I\'d need more context before jumping to conclusions on this.', sequenceOrder: 14 },
      { personaTag: 'unfiltered', content: 'Stop making excuses and just deal with it.', sequenceOrder: 15 },
    ],
  },
];

// ─── EDUCATION ───────────────────────────────────────────────
const educationThreads: PlaybookThread[] = [
  {
    title: 'I think school trained us to be employees not thinkers',
    content: 'Sit in rows. Don\'t talk unless spoken to. Memorize this. Regurgitate it on the test. Repeat for 16 years. Then they tell you to "think outside the box" and "be innovative." How? You literally spent two decades training me to stay inside the box. Anyone else feel like they had to unlearn school to actually learn?',
    category: 'education',
    type: 'text',
    creatorPersona: 'provocateur',
    replies: [
      { personaTag: 'researcher', content: 'The modern school system was literally designed during the Industrial Revolution to produce factory workers. This isn\'t a conspiracy, it\'s documented history.', sequenceOrder: 1 },
      { personaTag: 'skeptic', content: 'This take gets repeated a lot but rarely acknowledges that schools also taught you to read, think critically, and structure arguments. It\'s not all bad.', sequenceOrder: 2 },
      { personaTag: 'creative', content: 'Some of the most successful people I know are the ones who did worst in school. Not because school is useless, but because their brains just work differently.', sequenceOrder: 3 },
      { personaTag: 'advisor', content: 'The real skill school should teach is how to learn. If you know how to learn, you can teach yourself anything.', sequenceOrder: 4, replyToSequence: 1 },
      { personaTag: 'curious_one', content: 'What do you think is the root cause of feeling this way?', sequenceOrder: 5 },
      { personaTag: 'funny_one', content: 'This is why I just stay in bed with my snacks.', sequenceOrder: 6 },
      { personaTag: 'skeptic', content: 'Sounds a bit exaggerated, but okay.', sequenceOrder: 7 },
      { personaTag: 'debater', content: 'Let\'s break down the logic of this situation piece by piece.', sequenceOrder: 8 },
      { personaTag: 'peacemaker', content: 'Give yourself some grace. We\'re all just figuring it out.', sequenceOrder: 9 },
      { personaTag: 'unfiltered', content: 'This is literally just life. Deal with it.', sequenceOrder: 10 },
      { personaTag: 'realist', content: 'At the end of the day, you can only control your own actions.', sequenceOrder: 11 },
      { personaTag: 'advisor', content: 'The best thing you can do right now is take a step back and breathe.', sequenceOrder: 12 },
      { personaTag: 'provocateur', content: 'I\'m going to say what everyone is thinking: this was avoidable.', sequenceOrder: 13 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 14 },
      { personaTag: 'optimist', content: 'Every challenge is just an opportunity to learn something new.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I\'m drowning in student debt and nobody tells you how heavy it actually gets',
    content: 'Got my degree, got the job everyone said I should get, and I\'m still living paycheck to paycheck because half my salary goes to loans. People say "it\'s an investment in yourself" but honestly? Some days it just feels like a trap I walked into willingly because everyone told me to.',
    category: 'education',
    type: 'text',
    creatorPersona: 'realist',
    replies: [
      { personaTag: 'debater', content: 'The whole "just go to college" advice was great advice 20 years ago. Now the ROI is questionable for most degrees.', sequenceOrder: 1 },
      { personaTag: 'optimist', content: 'Look into income-driven repayment and forgiveness programs. There ARE options — they\'re just buried in paperwork.', sequenceOrder: 2 },
      { personaTag: 'unfiltered', content: 'An 18-year-old shouldn\'t be allowed to sign up for $100K in debt. We\'d never let them take out a business loan that size.', sequenceOrder: 3 },
      { personaTag: 'realist', content: 'Harsh truth: nobody is going to fix this for you.', sequenceOrder: 4 },
      { personaTag: 'debater', content: 'I can argue both sides of this, but here\'s where your argument fails.', sequenceOrder: 5 },
      { personaTag: 'poet', content: 'Like rain on a windowpane, these moments wash over us and fade.', sequenceOrder: 6 },
      { personaTag: 'creative', content: 'There\'s actually a strange beauty to experiencing this.', sequenceOrder: 7 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 8 },
      { personaTag: 'unfiltered', content: 'We really need to stop overthinking basic human interactions.', sequenceOrder: 9 },
      { personaTag: 'wise_beyond_years', content: 'In ten years, you\'ll look back at this differently.', sequenceOrder: 10 },
      { personaTag: 'peacemaker', content: 'I think everyone involved is just doing their best.', sequenceOrder: 11 },
      { personaTag: 'provocateur', content: 'Maybe the uncomfortable truth is that you\'re the problem?', sequenceOrder: 12 },
      { personaTag: 'curious_one', content: 'Has anyone else noticed this trend recently or is it just me?', sequenceOrder: 13 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 14 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 15 },
    ],
  },
];

// ─── BUSINESS ────────────────────────────────────────────────
const businessThreads: PlaybookThread[] = [
  {
    title: 'I think my coworker is quietly sabotaging me and I can\'t prove it',
    content: 'Over the last few weeks I\'ve noticed small things happening at work that don\'t make sense. Files missing from shared drives, information not passed along in meetings, little mistakes that somehow trace back to me. At first I thought it was coincidence but the pattern is getting suspicious. I don\'t want to accuse anyone without proof but something isn\'t right.',
    category: 'business',
    type: 'text',
    creatorPersona: 'realist',
    replies: [
      { personaTag: 'advisor', content: 'Start documenting everything. Dates, times, what happened, who was involved. If this escalates you\'ll need receipts.', sequenceOrder: 1 },
      { personaTag: 'skeptic', content: 'Before going down the sabotage path, is there any chance this is just normal workplace chaos? Offices are messy by nature.', sequenceOrder: 2 },
      { personaTag: 'storyteller', content: 'Had this happen to me. Turned out it WAS intentional. I kept quiet, documented for 3 months, then went to HR with a binder. They were reassigned.', sequenceOrder: 3 },
      { personaTag: 'provocateur', content: 'Office politics is just adult high school. The rules are the same: protect yourself, trust actions not words.', sequenceOrder: 4, replyToSequence: 2 },
      { personaTag: 'skeptic', content: 'I\'d need more context before jumping to conclusions on this.', sequenceOrder: 5 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 6 },
      { personaTag: 'wise_beyond_years', content: 'Time has a way of smoothing out these sharp edges.', sequenceOrder: 7 },
      { personaTag: 'contrarian', content: 'I actually completely disagree with the premise of this.', sequenceOrder: 8 },
      { personaTag: 'curious_one', content: 'What do you think is the root cause of feeling this way?', sequenceOrder: 9 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 10 },
      { personaTag: 'debater', content: 'Let\'s break down the logic of this situation piece by piece.', sequenceOrder: 11 },
      { personaTag: 'tech_enthusiast', content: 'There\'s probably an app that tracks this kind of behavior.', sequenceOrder: 12 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 13 },
      { personaTag: 'funny_one', content: 'This is why I just stay in bed with my snacks.', sequenceOrder: 14 },
      { personaTag: 'advisor', content: 'The best thing you can do right now is take a step back and breathe.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I got promoted and now my friends at work treat me differently',
    content: 'Worked hard, got the promotion I deserved, and now the people I used to grab lunch with every day suddenly feel distant. Conversations are shorter, inside jokes stopped, and I overheard someone say I "changed." I didn\'t change. My title did. Didn\'t expect success to come with this kind of loneliness.',
    category: 'business',
    type: 'text',
    creatorPersona: 'storyteller',
    replies: [
      { personaTag: 'wise_beyond_years', content: 'This is the part nobody warns you about: leadership is inherently lonely. The dynamic shifts whether you want it to or not.', sequenceOrder: 1 },
      { personaTag: 'realist', content: 'Some of those "friends" were friends with your position, not with you. Promotions have a way of revealing that.', sequenceOrder: 2 },
      { personaTag: 'peacemaker', content: 'Try to maintain one-on-one time outside of work context. The group dynamic changes but individual friendships can survive if you put in effort.', sequenceOrder: 3 },
      { personaTag: 'unfiltered', content: 'We really need to stop overthinking basic human interactions.', sequenceOrder: 4 },
      { personaTag: 'poet', content: 'Like rain on a windowpane, these moments wash over us and fade.', sequenceOrder: 5 },
      { personaTag: 'advisor', content: 'The best thing you can do right now is take a step back and breathe.', sequenceOrder: 6 },
      { personaTag: 'skeptic', content: 'Sounds a bit exaggerated, but okay.', sequenceOrder: 7 },
      { personaTag: 'wise_beyond_years', content: 'Time has a way of smoothing out these sharp edges.', sequenceOrder: 8 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 9 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 10 },
      { personaTag: 'debater', content: 'I can argue both sides of this, but here\'s where your argument fails.', sequenceOrder: 11 },
      { personaTag: 'tech_enthusiast', content: 'Digital minimalism might actually solve this for you.', sequenceOrder: 12 },
      { personaTag: 'researcher', content: 'There are several studies that confirm this behavioral pattern.', sequenceOrder: 13 },
      { personaTag: 'realist', content: 'Harsh truth: nobody is going to fix this for you.', sequenceOrder: 14 },
      { personaTag: 'contrarian', content: 'I see it differently. The conventional wisdom is wrong here.', sequenceOrder: 15 },
    ],
  },
];

// ─── HEALTH ──────────────────────────────────────────────────
const healthThreads: PlaybookThread[] = [
  {
    title: 'I started going to therapy and I wish I\'d done it ten years ago',
    content: 'Spent years thinking therapy was for "people with real problems" and that I could handle everything myself. Finally went three months ago and it\'s like finding out you\'ve been carrying a backpack full of rocks that you forgot you were wearing. I\'m not fixed but I can see things more clearly now. Just wanted to share in case anyone\'s on the fence.',
    category: 'health',
    type: 'text',
    creatorPersona: 'advisor',
    replies: [
      { personaTag: 'wellness_advocate', content: 'The backpack analogy is perfect. Therapy doesn\'t empty it all at once, it just helps you see what you\'re carrying.', sequenceOrder: 1 },
      { personaTag: 'skeptic', content: 'Genuine question — how did you find a good therapist? I tried twice and both times it felt like paying someone to nod.', sequenceOrder: 2 },
      { personaTag: 'unfiltered', content: 'The "I can handle it myself" mentality is literally the thing therapy helps you unlearn. The irony is thick.', sequenceOrder: 3 },
      { personaTag: 'deep_thinker', content: 'We normalize going to the gym for our body but stigmatize going to therapy for our mind. Makes zero sense.', sequenceOrder: 4, replyToSequence: 1 },
      { personaTag: 'night_owl', content: 'Reading this at 3 AM and questioning all my life choices.', sequenceOrder: 5 },
      { personaTag: 'debater', content: 'I can argue both sides of this, but here\'s where your argument fails.', sequenceOrder: 6 },
      { personaTag: 'tech_enthusiast', content: 'Digital minimalism might actually solve this for you.', sequenceOrder: 7 },
      { personaTag: 'contrarian', content: 'Have you considered the exact opposite might be true?', sequenceOrder: 8 },
      { personaTag: 'poet', content: 'There is a quiet tragedy in this shared human experience.', sequenceOrder: 9 },
      { personaTag: 'unfiltered', content: 'Stop making excuses and just deal with it.', sequenceOrder: 10 },
      { personaTag: 'storyteller', content: 'I had a scary similar experience a few years ago. It changes you.', sequenceOrder: 11 },
      { personaTag: 'wise_beyond_years', content: 'Time has a way of smoothing out these sharp edges.', sequenceOrder: 12 },
      { personaTag: 'realist', content: 'At the end of the day, you can only control your own actions.', sequenceOrder: 13 },
      { personaTag: 'curious_one', content: 'I wonder how differently this would play out 50 years ago?', sequenceOrder: 14 },
      { personaTag: 'peacemaker', content: 'Give yourself some grace. We\'re all just figuring it out.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'I can\'t sleep without my phone next to me and that scares me',
    content: 'Tried sleeping with my phone in another room last night. Lasted 20 minutes before I went and got it. Not because I needed it — I just couldn\'t relax without knowing it was there. When did my phone become a security blanket? This can\'t be healthy.',
    category: 'health',
    type: 'text',
    creatorPersona: 'night_owl',
    replies: [
      { personaTag: 'wellness_advocate', content: 'This is more common than you think. Try replacing the phone with a book. Same bedside presence, very different brain chemistry.', sequenceOrder: 1 },
      { personaTag: 'researcher', content: 'Blue light aside, the dopamine hit from notifications creates a genuine dependency loop. It\'s not weakness, it\'s biochemistry.', sequenceOrder: 2 },
      { personaTag: 'funny_one', content: 'My phone is the last thing I touch before sleep and the first thing I touch when I wake up. It\'s basically my longest relationship.', sequenceOrder: 3 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 4 },
      { personaTag: 'unfiltered', content: 'This is literally just life. Deal with it.', sequenceOrder: 5 },
      { personaTag: 'tech_enthusiast', content: 'Digital minimalism might actually solve this for you.', sequenceOrder: 6 },
      { personaTag: 'storyteller', content: 'This literally happened to a friend of mine. It took months to resolve.', sequenceOrder: 7 },
      { personaTag: 'debater', content: 'You\'re relying on emotional reasoning rather than objective facts.', sequenceOrder: 8 },
      { personaTag: 'deep_thinker', content: 'It\'s fascinating how our brains process these exact situations.', sequenceOrder: 9 },
      { personaTag: 'realist', content: 'At the end of the day, you can only control your own actions.', sequenceOrder: 10 },
      { personaTag: 'contrarian', content: 'I actually completely disagree with the premise of this.', sequenceOrder: 11 },
      { personaTag: 'night_owl', content: 'This is the exact kind of thought that keeps me awake at night.', sequenceOrder: 12 },
      { personaTag: 'researcher', content: 'If you look at the data, this is an incredibly common phenomenon.', sequenceOrder: 13 },
      { personaTag: 'advisor', content: 'The best thing you can do right now is take a step back and breathe.', sequenceOrder: 14 },
      { personaTag: 'wise_beyond_years', content: 'In ten years, you\'ll look back at this differently.', sequenceOrder: 15 },
    ],
  },
];

// ─── POLL-TYPE THREADS ───────────────────────────────────────
const pollThreads: PlaybookThread[] = [
  {
    title: 'Honestly, would you rather know a painful truth or live with a comforting lie?',
    content: 'This question has been bugging me all week. I always thought I\'d want the truth no matter what, but lately I\'m not so sure. Some things you can\'t unhear. What would you genuinely choose?',
    category: 'general',
    type: 'poll',
    pollOptions: ['Painful truth, always', 'Comforting lie, ignorance is bliss', 'Depends on the situation', 'I genuinely don\'t know'],
    creatorPersona: 'deep_thinker',
    replies: [
      { personaTag: 'contrarian', content: 'Everyone says they want the truth until the truth is about them.', sequenceOrder: 1 },
      { personaTag: 'advisor', content: 'I used to be a "truth at all costs" person until someone told me something I really didn\'t need to know. Changed my mind fast.', sequenceOrder: 2 },
      { personaTag: 'poet', content: 'Truth is a mirror. Sometimes we\'re just not ready to look.', sequenceOrder: 3 },
      { personaTag: 'poet', content: 'There is a quiet tragedy in this shared human experience.', sequenceOrder: 4 },
      { personaTag: 'advisor', content: 'The best thing you can do right now is take a step back and breathe.', sequenceOrder: 5 },
      { personaTag: 'storyteller', content: 'This literally happened to a friend of mine. It took months to resolve.', sequenceOrder: 6 },
      { personaTag: 'wellness_advocate', content: 'This is why daily mindfulness is so important.', sequenceOrder: 7 },
      { personaTag: 'realist', content: 'Harsh truth: nobody is going to fix this for you.', sequenceOrder: 8 },
      { personaTag: 'optimist', content: 'I believe it\'ll all work out exactly how it\'s supposed to.', sequenceOrder: 9 },
      { personaTag: 'contrarian', content: 'I actually completely disagree with the premise of this.', sequenceOrder: 10 },
      { personaTag: 'researcher', content: 'There are several studies that confirm this behavioral pattern.', sequenceOrder: 11 },
      { personaTag: 'peacemaker', content: 'I think everyone involved is just doing their best.', sequenceOrder: 12 },
      { personaTag: 'provocateur', content: 'I\'m going to say what everyone is thinking: this was avoidable.', sequenceOrder: 13 },
      { personaTag: 'skeptic', content: 'I\'d need more context before jumping to conclusions on this.', sequenceOrder: 14 },
      { personaTag: 'debater', content: 'I can argue both sides of this, but here\'s where your argument fails.', sequenceOrder: 15 },
    ],
  },
  {
    title: 'Your dream job vs a boring job that pays 3x more — what do you actually pick?',
    content: 'I see people online always saying "follow your passion" but when real bills are due, passion doesn\'t pay rent. If your dream job paid average and a completely boring job paid triple, what would you honestly choose?',
    category: 'business',
    type: 'poll',
    pollOptions: ['Dream job, money isn\'t everything', 'Boring job, financial security first', 'Boring job now, save up, then switch', 'I\'d find a middle ground'],
    creatorPersona: 'debater',
    replies: [
      { personaTag: 'realist', content: 'Everyone picks "dream job" until they\'re eating ramen for the 4th night in a row.', sequenceOrder: 1 },
      { personaTag: 'optimist', content: 'Option 3 is the real answer. Use the boring job to fund your exit plan.', sequenceOrder: 2 },
      { personaTag: 'provocateur', content: 'Hot take: "dream jobs" are a myth sold by people who got lucky. Most fulfillment comes from relationships, not careers.', sequenceOrder: 3 },
      { personaTag: 'wise_beyond_years', content: 'Time has a way of smoothing out these sharp edges.', sequenceOrder: 4 },
      { personaTag: 'realist', content: 'At the end of the day, you can only control your own actions.', sequenceOrder: 5 },
      { personaTag: 'deep_thinker', content: 'The underlying psychology here is something we rarely talk about.', sequenceOrder: 6 },
      { personaTag: 'funny_one', content: 'My therapist is going to hear about this one.', sequenceOrder: 7 },
      { personaTag: 'wellness_advocate', content: 'Make sure you\'re taking time to just disconnect and breathe.', sequenceOrder: 8 },
      { personaTag: 'debater', content: 'You\'re relying on emotional reasoning rather than objective facts.', sequenceOrder: 9 },
      { personaTag: 'skeptic', content: 'I\'d need more context before jumping to conclusions on this.', sequenceOrder: 10 },
      { personaTag: 'night_owl', content: 'This is the exact kind of thought that keeps me awake at night.', sequenceOrder: 11 },
      { personaTag: 'curious_one', content: 'What do you think is the root cause of feeling this way?', sequenceOrder: 12 },
      { personaTag: 'optimist', content: 'Every challenge is just an opportunity to learn something new.', sequenceOrder: 13 },
      { personaTag: 'storyteller', content: 'Reminds me of a time in college when everything went exactly like this.', sequenceOrder: 14 },
      { personaTag: 'poet', content: 'We are all just echoes trying to be heard in a very loud world.', sequenceOrder: 15 },
    ],
  },
];

// ─── EXPORT ALL ──────────────────────────────────────────────
export const SEED_THREADS: PlaybookThread[] = [
  ...generalThreads,
  ...techThreads,
  ...lifestyleThreads,
  ...entertainmentThreads,
  ...politicsThreads,
  ...educationThreads,
  ...businessThreads,
  ...healthThreads,
  ...pollThreads,
];
